/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ici3241.proyecto;

import java.util.ArrayList;

/**
 *
 * @author mandr
 */
public class GUIAgregarPlan extends javax.swing.JDialog {
    
    ArrayList <Plan> listaPlanes; 

    /**
     * Creates new form GUIAgregarPlan
     */
    public GUIAgregarPlan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    void limpiarCampos() {
        this.campoNombrePlan.setText("");
        this.campoPrecioPlan.setText("");
        this.campoNavegacionPlan.setText("");
        this.campoMinutosPlan.setText("");
        this.campoMensajesPlan.setText("");    
    }
    
    void inicializar() {
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNombrePlan = new javax.swing.JLabel();
        labelPrecioPlan = new javax.swing.JLabel();
        labelNavegacionPlan = new javax.swing.JLabel();
        labelMinutosPlan = new javax.swing.JLabel();
        labelMensajesPlan = new javax.swing.JLabel();
        campoNombrePlan = new javax.swing.JTextField();
        campoPrecioPlan = new javax.swing.JTextField();
        campoNavegacionPlan = new javax.swing.JTextField();
        campoMinutosPlan = new javax.swing.JTextField();
        campoMensajesPlan = new javax.swing.JTextField();
        botonLimpiarCampos = new javax.swing.JButton();
        botonAgregarPlan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setText("Agregar Plan");

        labelNombrePlan.setText("Nombre:");

        labelPrecioPlan.setText("Precio:");

        labelNavegacionPlan.setText("Navegacion:");

        labelMinutosPlan.setText("Minutos:");

        labelMensajesPlan.setText("Mensajes:");

        campoNombrePlan.setText("jTextField1");

        campoPrecioPlan.setText("jTextField2");

        campoNavegacionPlan.setText("jTextField3");

        campoMinutosPlan.setText("jTextField4");

        campoMensajesPlan.setText("jTextField5");

        botonLimpiarCampos.setText("Limpiar");
        botonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarCamposActionPerformed(evt);
            }
        });

        botonAgregarPlan.setText("Agregar");
        botonAgregarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMensajesPlan)
                                    .addComponent(labelMinutosPlan)
                                    .addComponent(labelNavegacionPlan)
                                    .addComponent(labelPrecioPlan)
                                    .addComponent(labelNombrePlan))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNombrePlan, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(campoPrecioPlan)
                                    .addComponent(campoNavegacionPlan)
                                    .addComponent(campoMinutosPlan)
                                    .addComponent(campoMensajesPlan)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonLimpiarCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAgregarPlan)))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(37, 37, 37)
                        .addComponent(labelNombrePlan))
                    .addComponent(campoNombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecioPlan)
                    .addComponent(campoPrecioPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNavegacionPlan)
                    .addComponent(campoNavegacionPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinutosPlan)
                    .addComponent(campoMinutosPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMensajesPlan)
                    .addComponent(campoMensajesPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiarCampos)
                    .addComponent(botonAgregarPlan))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonLimpiarCamposActionPerformed

    private void botonAgregarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPlanActionPerformed
        String nombre = this.campoNombrePlan.getText();
        int precio = Integer.parseInt(this.campoPrecioPlan.getText());
        int navegacion = Integer.parseInt(this.campoNavegacionPlan.getText());
        String minutos = this.campoMinutosPlan.getText();
        int mensajes = Integer.parseInt(this.campoMensajesPlan.getText());
        Plan plan = new Plan(nombre, precio, navegacion, minutos, mensajes);
        listaPlanes.add(plan);
        limpiarCampos();
    }//GEN-LAST:event_botonAgregarPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIAgregarPlan dialog = new GUIAgregarPlan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarPlan;
    private javax.swing.JButton botonLimpiarCampos;
    private javax.swing.JTextField campoMensajesPlan;
    private javax.swing.JTextField campoMinutosPlan;
    private javax.swing.JTextField campoNavegacionPlan;
    private javax.swing.JTextField campoNombrePlan;
    private javax.swing.JTextField campoPrecioPlan;
    private javax.swing.JLabel labelMensajesPlan;
    private javax.swing.JLabel labelMinutosPlan;
    private javax.swing.JLabel labelNavegacionPlan;
    private javax.swing.JLabel labelNombrePlan;
    private javax.swing.JLabel labelPrecioPlan;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
