/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ici3241.proyecto;

import java.util.ArrayList;

/**
 *
 * @author mandr
 */
public class GUIAgregarCliente extends javax.swing.JDialog {
    
    private ArrayList <Cliente> listaClientes;    

    /**
     * Creates new form GUIAgregarCliente
     */
    public GUIAgregarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    void limpiarCampos() {
        this.campoNombreCliente.setText("");
        this.campoNumeroCliente.setText("");
        this.campoDireccionCliente.setText("");
        this.campoRUTCliente.setText("");        
    }
    
    void inicializar() {
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNombreCliente = new javax.swing.JLabel();
        labelRUTCliente = new javax.swing.JLabel();
        labelDireccionCliente = new javax.swing.JLabel();
        labelNumeroCliente = new javax.swing.JLabel();
        labelPlanCliente = new javax.swing.JLabel();
        campoNombreCliente = new javax.swing.JTextField();
        campoRUTCliente = new javax.swing.JTextField();
        campoDireccionCliente = new javax.swing.JTextField();
        campoNumeroCliente = new javax.swing.JTextField();
        campoPlanCliente = new javax.swing.JComboBox<>();
        botonLimpiarCampos = new javax.swing.JButton();
        botonAgregarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setText("Agregar Cliente");

        labelNombreCliente.setText("Nombre:");

        labelRUTCliente.setText("RUT:");

        labelDireccionCliente.setText("Dirección:");

        labelNumeroCliente.setText("Número telefónico:");

        labelPlanCliente.setText("Plan:");

        campoNombreCliente.setText("jTextField1");

        campoRUTCliente.setText("jTextField2");

        campoDireccionCliente.setText("jTextField3");

        campoNumeroCliente.setText("jTextField4");

        campoPlanCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un plan", "Iron", "Bronze", "Gold", "Platinum", "Diamond", "Personalizado" }));

        botonLimpiarCampos.setText("Limpiar");
        botonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarCamposActionPerformed(evt);
            }
        });

        botonAgregarCliente.setText("Agregar");
        botonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(botonLimpiarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAgregarCliente)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNumeroCliente)
                            .addComponent(labelNombreCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRUTCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDireccionCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPlanCliente, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombreCliente)
                            .addComponent(campoRUTCliente)
                            .addComponent(campoDireccionCliente)
                            .addComponent(campoNumeroCliente)
                            .addComponent(campoPlanCliente, 0, 176, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelTitulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreCliente)
                    .addComponent(campoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRUTCliente)
                    .addComponent(campoRUTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccionCliente)
                    .addComponent(campoDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroCliente)
                    .addComponent(campoNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlanCliente)
                    .addComponent(campoPlanCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiarCampos)
                    .addComponent(botonAgregarCliente))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarClienteActionPerformed
        String nombre = this.campoNombreCliente.getText();
        String rut = this.campoRUTCliente.getText();
        String direccion = this.campoDireccionCliente.getText();
        String numero = this.campoNumeroCliente.getText();
        String plan = this.campoPlanCliente.getItemAt(this.campoPlanCliente.getSelectedIndex());        
        Cliente cliente = new Cliente(nombre, rut, direccion, numero, plan);
        listaClientes.add(cliente);
        limpiarCampos();
    }//GEN-LAST:event_botonAgregarClienteActionPerformed

    private void botonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonLimpiarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIAgregarCliente dialog = new GUIAgregarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarCliente;
    private javax.swing.JButton botonLimpiarCampos;
    private javax.swing.JTextField campoDireccionCliente;
    private javax.swing.JTextField campoNombreCliente;
    private javax.swing.JTextField campoNumeroCliente;
    private javax.swing.JComboBox<String> campoPlanCliente;
    private javax.swing.JTextField campoRUTCliente;
    private javax.swing.JLabel labelDireccionCliente;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JLabel labelNumeroCliente;
    private javax.swing.JLabel labelPlanCliente;
    private javax.swing.JLabel labelRUTCliente;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
